config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
 controller :sessions do
 get 'login' => :new
 post 'login' => :create
 delete 'logout' => :destroy
 end

 get 'signup', to: 'users#new'
 resources :user_steps

 resources :users, except: [:new] do
  resources :skills
  resources :additional_informations
  resources :projects
  resources :educations
  resources :work_experiences
  resources :personaldetail
  resources :template
 end
  get 'sessions/create'
  get 'sessions/destroy'
  
 
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/additional_information.rb
class AdditionalInformation < ApplicationRecord
    belongs_to :user
 
end

app/controllers/additional_informations_controller.rb
class AdditionalInformationsController < ApplicationController
  before_action :set_additional_information, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /additional_informations
  # GET /additional_informations.json
  def index
    @additional_informations = AdditionalInformation.all
  end

  # GET /additional_informations/1
  # GET /additional_informations/1.json
  def show
  end

  # GET /additional_informations/new
  def new
    @additional_information = AdditionalInformation.new
  end

  # GET /additional_informations/1/edit
  def edit
  end

  # POST /additional_informations
  # POST /additional_informations.json
  def create
    @additional_information = AdditionalInformation.new(additional_information_params)
    @additional_information.user_id = @user.id

    respond_to do |format|
      if @additional_information.save
        format.html { redirect_to user_additional_informations_path(@user), notice: 'Additional information was successfully created.' }
        format.json { render :show, status: :created, location: @additional_information }
      else
        format.html { render :new }
        format.json { render json: @additional_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /additional_informations/1
  # PATCH/PUT /additional_informations/1.json
  def update
    respond_to do |format|
      if @additional_information.update(additional_information_params)
        format.html { redirect_to user_additional_informations_path(@user), notice: 'Additional information was successfully updated.' }
        format.json { render :show, status: :ok, location: @additional_information }
      else
        format.html { render :edit }
        format.json { render json: @additional_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /additional_informations/1
  # DELETE /additional_informations/1.json
  def destroy
    @additional_information.destroy
    respond_to do |format|
      format.html { redirect_to user_additional_informations_path(@user), notice: 'Additional information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_additional_information
      @additional_information = AdditionalInformation.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def additional_information_params
      params.require(:additional_information).permit(:achievements, :hobbies, :strengths, :weaknesses)
    end
end

app/helpers/additional_informations_helper.rb
module AdditionalInformationsHelper
end

app/views/additional_informations/_form.html.erb
<%= form_with(model: additional_information,url:user_additional_informations_path,method: :post, local: true) do |form| %>
  <% if additional_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(additional_information.errors.count, "error") %> prohibited this additional_information from being saved:</h2>

      <ul>
        <% additional_information.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :achievements %>
    <%= form.text_area :achievements %>
  </div>

  <div class="field">
    <%= form.label :hobbies %>
    <%= form.text_area :hobbies %>
  </div>

  <div class="field">
    <%= form.label :strengths %>
    <%= form.text_area :strengths %>
  </div>

  <div class="field">
    <%= form.label :weaknesses %>
    <%= form.text_area :weaknesses %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/additional_informations/edit.html.erb
<h1>Editing Additional Information</h1>

<%= render 'form', additional_information: @additional_information %>

<%= link_to 'Show', @additional_information %> |
<%= link_to 'Back', additional_informations_path %>

app/views/additional_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Additional Informations</h1>

<table>
  <thead>
    <tr>
      <th>Achievements</th>
      <th>Hobbies</th>
      <th>Strengths</th>
      <th>Weaknesses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @additional_informations.each do |additional_information| %>
      <tr>
        <td><%= additional_information.achievements %></td>
        <td><%= additional_information.hobbies %></td>
        <td><%= additional_information.strengths %></td>
        <td><%= additional_information.weaknesses %></td>
        <td><%= link_to 'Edit Education', edit_user_additional_information_path(user_id: @user,id: additional_information) %></td>
        <td><%= link_to 'Destroy',user_additional_information_path(user_id: @user,id: additional_information), method: :delete, data: { confirm: 'Are you sure?' } %></td> 
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_tag 'Edit Additional Information',id: "edit_education_form" %>
<div id="additional_information_form">
<%= render 'form', additional_information: AdditionalInformation.new() ,form_url: question.comments}%>
</div>

app/views/additional_informations/new.html.erb
<h1>New Additional Information</h1>

<%= render 'form', additional_information: @additional_information %>

app/views/additional_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Achievements:</strong>
  <%= @additional_information.achievements %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @additional_information.hobbies %>
</p>

<p>
  <strong>Strengths:</strong>
  <%= @additional_information.strengths %>
</p>

<p>
  <strong>Weaknesses:</strong>
  <%= @additional_information.weaknesses %>
</p>

<%= link_to 'Edit', edit_additional_information_path(@additional_information) %> |
<%= link_to 'Back', additional_informations_path %>