config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
 controller :sessions do
 get 'login' => :new
 post 'login' => :create
 delete 'logout' => :destroy
 end

 get 'signup', to: 'users#new'
 resources :user_steps

 resources :users, except: [:new] do
  resources :skills
  resources :additional_informations
  resources :projects
  resources :educations
  resources :work_experiences
  resources :personaldetail
  resources :template
 end
  get 'sessions/create'
  get 'sessions/destroy'
  
 
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/work_experience.rb
class WorkExperience < ApplicationRecord
    belongs_to :user
    NON_VALIDATABLE_ATTRS = ["id", "created_at", "updated_at", "description","location"]
    VALIDATABLE_ATTRS = WorkExperience.attribute_names.reject{|attr| NON_VALIDATABLE_ATTRS.include?(attr)}
    validates_presence_of VALIDATABLE_ATTRS
end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /work_experiences
  # GET /work_experiences.json
  def index
    @work_experiences = WorkExperience.all
  end

  # GET /work_experiences/1
  # GET /work_experiences/1.json
  def show
  end

  # GET /work_experiences/new
  def new
    @work_experience = WorkExperience.new
  end

  # GET /work_experiences/1/edit
  def edit
  end

  # POST /work_experiences
  # POST /work_experiences.json
  def create
    @work_experience = WorkExperience.new(work_experience_params)

    respond_to do |format|
      if @work_experience.save
        format.html { redirect_to edit_user_path(@user), notice: 'Work experience was successfully created.' }
        format.json { render :show, status: :created, location: @work_experience }
      else
        format.html { render :new }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_experiences/1
  # PATCH/PUT /work_experiences/1.json
  def update
    respond_to do |format|
      if @work_experience.update(work_experience_params)
        format.html { redirect_to edit_user_path(@user), notice: 'Work experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_experience }
      else
        format.html { render :edit }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_experiences/1
  # DELETE /work_experiences/1.json
  def destroy
    @work_experience.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_path(@user), notice: 'Work experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_experience
      @work_experience = WorkExperience.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end
    # Only allow a list of trusted parameters through.
    def work_experience_params
      params.require(:work_experience).permit(:company, :start_date, :end_date, :position)
    end
end

app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
end

app/views/work_experiences/_form.html.erb
<%= form_with(model: work_experience, local: true) do |form| %>
  <% if work_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_experience.errors.count, "error") %> prohibited this work_experience from being saved:</h2>

      <ul>
        <% work_experience.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/work_experiences/edit.html.erb
<h1>Editing Work Experience</h1>

<%= render 'form', work_experience: @work_experience %>

<%= link_to 'Show', @work_experience %> |
<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Experiences</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_experiences.each do |work_experience| %>
      <tr>
        <td><%= work_experience.company %></td>
        <td><%= work_experience.start_date %></td>
        <td><%= work_experience.end_date %></td>
        <td><%= work_experience.position %></td>
        <td><%= link_to 'Show', work_experience %></td>
        <td><%= link_to 'Edit', edit_work_experience_path(work_experience) %></td>
        <td><%= link_to 'Destroy', work_experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Experience', new_work_experience_path %>

app/views/work_experiences/new.html.erb
<h1>New Work Experience</h1>

<%= render 'form', work_experience: @work_experience %>

<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @work_experience.company %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @work_experience.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @work_experience.end_date %>
</p>

<p>
  <strong>Position:</strong>
  <%= @work_experience.position %>
</p>

<%= link_to 'Edit', edit_work_experience_path(@work_experience) %> |
<%= link_to 'Back', work_experiences_path %>