config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
 controller :sessions do
 get 'login' => :new
 post 'login' => :create
 delete 'logout' => :destroy
 end

 get 'signup', to: 'users#new'
 resources :user_steps

 resources :users, except: [:new] do
  resources :skills
  resources :additional_informations
  resources :projects
  resources :educations
  resources :work_experiences
  resources :personaldetail
  resources :template
 end
  get 'sessions/create'
  get 'sessions/destroy'
  
 
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/education.rb
class Education < ApplicationRecord
    belongs_to :user
    NON_VALIDATABLE_ATTRS = ["id", "created_at", "updated_at", "specification"]
    VALIDATABLE_ATTRS = Education.attribute_names.reject{|attr| NON_VALIDATABLE_ATTRS.include?(attr)}
    validates_presence_of VALIDATABLE_ATTRS
   
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
  #byebug
    @education = Education.new(education_params)
    @education.user_id = @user.id
    respond_to do |format|
      if @education.save!
        format.html {  redirect_to user_educations_path(@user), notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to user_educations_path(@user), notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html {redirect_to user_educations_path(@user), notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def education_params
      params.require(:education).permit(:institute_name, :qualification,:specification, :start_date, :end_date, :marks)
    end
  
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/edit.html.erb
<h1>Editing Education</h1>

<%= render 'form', education: @education %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Educations</h1>

<table>
  <thead>
    <tr>
      <th>Institute name</th>
      <th>Qualification</th>
      <th>Specification</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Marks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.institute_name %></td>
        <td><%= education.qualification %></td>
        <td><%= education.specification %></td>
        <td><%= education.start_date %></td>
        <td><%= education.end_date %></td>
        <td><%= education.marks %></td>
        <td><%= link_to 'Edit Education', edit_user_education_path(user_id: @user,id: education) %></td>
        <td><%= link_to 'Destroy',user_education_path(user_id: @user,id: education), method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Institute name:</strong>
  <%= @education.institute_name %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @education.qualification %>
</p>

<p>
  <strong>Specification:</strong>
  <%= @education.specification %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @education.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @education.end_date %>
</p>

<p>
  <strong>Marks:</strong>
  <%= @education.marks %>
</p>